version: '3'

services:
  mongo:
    image: 'mongo:latest'
    ports:
      - '27017:27017'

  api:
    build:
      context: './'
    volumes:
      - './:/home/node/worker'
    ports:
      - '3000:3000'
      - '9229:9229'
    depends_on:
      - mongo
